spring:
  datasource:
    driver-class-name: org.h2.Driver
    #init schema
    schema: classpath:db/schema.sql
    #init data
    data: classpath:db/data.sql
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password: 123456
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        web-admin-password: 123456

logging:
  level:
    com.example.serial.data.mapper: debug
